### ISSUE TITLE
there may be a typo

### ISSUE THREAD

**Issue by z16166** [apriorit/IconOverlayHandler#1]
wrong:
`    STDMETHODIMP OverlayIconExt::GetPriority(int* pPriority)
    {
        if(*pPriority)
        {
            return E_INVALIDARG;
        }
`

correct:
`    STDMETHODIMP OverlayIconExt::GetPriority(int* pPriority)
    {
        if(!pPriority)
        {
            return E_INVALIDARG;
        }
`

**Comment by SergiusTheBest** [comment]
Indeed. Thank you for spotting it!
